# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |intro_to_the_web| "https://github.com/bryn9696/#{intro_to_the_web}" }

ruby '3.0.0'

group :development, :test do
  gem 'rspec'
  gem 'sinatra'
  gem 'capybara'
end

gem "rack", "~> 2.2"
gem "sinatra-contrib", "~> 2.1"
gem "puma", "~> 5.5"
